image:
  file: .gitpod.Dockerfile

ports:
  - name: Rails server
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: PostgreSQL server
    port: 5432
    onOpen: ignore

tasks:
  - name: Installing Dependencies
    init: |
      bundle install &&
      yarn install
      gp sync-done installs
    openMode: split-left
  - name: create database & start server
    init: gp sync-await installs
    command: |
      rake db:create
      rails server -b 0.0.0.0
    openMode: split-right

vscode:
  extensions:
    - rebornix.ruby

jetbrains:
  rubymine:
    prebuilds:
      version: both
